name: Supabase Keep-Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # Cada 5 minutos
  workflow_dispatch:        # Ejecución manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          curl -s "https://dmmqaexxgghiuzjgtrtj.supabase.co/rest/v1/funkos?limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
           